<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $website
 * @property string $image
 * @property string $icon
 * @property sfGuardUser $User
 * 
 * @method string             getName()        Returns the current record's "name" value
 * @method string             getDescription() Returns the current record's "description" value
 * @method string             getWebsite()     Returns the current record's "website" value
 * @method string             getImage()       Returns the current record's "image" value
 * @method string             getIcon()        Returns the current record's "icon" value
 * @method sfGuardUser        getUser()        Returns the current record's "User" value
 * @method sfGuardUserProfile setName()        Sets the current record's "name" value
 * @method sfGuardUserProfile setDescription() Sets the current record's "description" value
 * @method sfGuardUserProfile setWebsite()     Sets the current record's "website" value
 * @method sfGuardUserProfile setImage()       Sets the current record's "image" value
 * @method sfGuardUserProfile setIcon()        Sets the current record's "icon" value
 * @method sfGuardUserProfile setUser()        Sets the current record's "User" value
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}