<?php

/**
 * BasePresentationUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $presentation_id
 * @property integer $user_id
 * 
 * @method integer          getPresentationId()  Returns the current record's "presentation_id" value
 * @method integer          getUserId()          Returns the current record's "user_id" value
 * @method PresentationUser setPresentationId()  Sets the current record's "presentation_id" value
 * @method PresentationUser setUserId()          Sets the current record's "user_id" value
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePresentationUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presentation_user');
        $this->hasColumn('presentation_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}