<?php

/**
 * BaseConference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Events
 * 
 * @method string              getTitle()  Returns the current record's "title" value
 * @method Doctrine_Collection getEvents() Returns the current record's "Events" collection
 * @method Conference          setTitle()  Sets the current record's "title" value
 * @method Conference          setEvents() Sets the current record's "Events" collection
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConference extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conference');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Event as Events', array(
             'local' => 'id',
             'foreign' => 'conference_id'));

        $sluggable0 = new Doctrine_Template_Sluggable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}