<?php

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $region_id
 * @property string $name
 * @property Region $Region
 * @property Doctrine_Collection $Events
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method integer             getRegionId()  Returns the current record's "region_id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Region              getRegion()    Returns the current record's "Region" value
 * @method Doctrine_Collection getEvents()    Returns the current record's "Events" collection
 * @method City                setId()        Sets the current record's "id" value
 * @method City                setRegionId()  Sets the current record's "region_id" value
 * @method City                setName()      Sets the current record's "name" value
 * @method City                setRegion()    Sets the current record's "Region" value
 * @method City                setEvents()    Sets the current record's "Events" collection
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('region_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('orderBy', 'name ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));

        $this->hasMany('Event as Events', array(
             'local' => 'id',
             'foreign' => 'city_id'));

        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($sluggable0);
    }
}