<?php

/**
 * BasePresentation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $content_id
 * @property Event $Event
 * @property Content $Content
 * @property Doctrine_Collection $Speakers
 * @property Doctrine_Collection $PresentationUser
 * 
 * @method integer             getEventId()          Returns the current record's "event_id" value
 * @method integer             getContentId()        Returns the current record's "content_id" value
 * @method Event               getEvent()            Returns the current record's "Event" value
 * @method Content             getContent()          Returns the current record's "Content" value
 * @method Doctrine_Collection getSpeakers()         Returns the current record's "Speakers" collection
 * @method Doctrine_Collection getPresentationUser() Returns the current record's "PresentationUser" collection
 * @method Presentation        setEventId()          Sets the current record's "event_id" value
 * @method Presentation        setContentId()        Sets the current record's "content_id" value
 * @method Presentation        setEvent()            Sets the current record's "Event" value
 * @method Presentation        setContent()          Sets the current record's "Content" value
 * @method Presentation        setSpeakers()         Sets the current record's "Speakers" collection
 * @method Presentation        setPresentationUser() Sets the current record's "PresentationUser" collection
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePresentation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presentation');
        $this->hasColumn('event_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('content_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));


        $this->index('event_id_content_id', array(
             'fields' => 
             array(
              0 => 'event_id',
              1 => 'content_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser as Speakers', array(
             'refClass' => 'PresentationUser',
             'local' => 'presentation_id',
             'foreign' => 'user_id'));

        $this->hasMany('PresentationUser', array(
             'local' => 'id',
             'foreign' => 'presentation_id'));
    }
}