<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $name
 * @property Country $Country
 * @property Doctrine_Collection $Cities
 * 
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Country             getCountry()    Returns the current record's "Country" value
 * @method Doctrine_Collection getCities()     Returns the current record's "Cities" collection
 * @method Region              setCountryId()  Sets the current record's "country_id" value
 * @method Region              setName()       Sets the current record's "name" value
 * @method Region              setCountry()    Sets the current record's "Country" value
 * @method Region              setCities()     Sets the current record's "Cities" collection
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('country_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('orderBy', 'name ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasMany('City as Cities', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($sluggable0);
    }
}