homepage:
  url: /
  param:
    module: homepage
    action: index

account:
  url: /account
  param:
    module: user
    action: edit

login:
  url: /login
  param:
    module: sfTwitterAuth
    action: login

login_error:
  url: /login/error
  param:
    module: sfTwitterAuth
    action: failed

logout:
  url: /logout
  param:
    module: sfTwitterAuth
    action: logout

profile:
  class: sfDoctrineRoute
  url: /user/:username
  options:
    model: sfGuardUser
    type: object
  param:
    module: user
    action: show