homepage:
  url: /
  param:
    module: homepage
    action: index

account:
  url: /account
  param:
    module: user
    action: edit

login:
  url: /login
  param:
    module: sfTwitterAuth
    action: login

login_error:
  url: /login/error
  param:
    module: sfTwitterAuth
    action: failed

logout:
  url: /logout
  param:
    module: sfTwitterAuth
    action: logout

new:
  url: /new
  param:
    module: event
    action: new

event:
  class: sfDoctrineRoute
  url: /:slug
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: show

event_action:
  class: sfDoctrineRoute
  url: /:slug/:action
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: [attend,watch,favourite,organise,speak,unattend,unwatch,unfavourite,unorganise,unspeak]

profile:
  class: sfDoctrineRoute
  url: /user/:username
  options:
    model: sfGuardUser
    type: object
  param:
    module: user
    action: show