homepage:
  url: /
  param:
    module: homepage
    action: index

account:
  url: /account
  param:
    module: user
    action: edit

login:
  url: /login
  param:
    module: sfTwitterAuth
    action: login

login_error:
  url: /login/error
  param:
    module: sfTwitterAuth
    action: failed

logout:
  url: /logout
  param:
    module: sfTwitterAuth
    action: logout

new:
  url: /new
  param:
    module: event
    action: new

user_search:
  url: /user/search
  param:
    module: user
    action: search
    sf_format: json

user_search_query:
  url: /user/search/:query
  param:
    module: user
    action: search
    sf_format: json

user_twitter_search:
  url: /user/twitter/search
  param:
    module: user
    action: twitterSearch
    sf_format: json

user_twitter_search_query:
  url: /user/twitter/search/:query
  param:
    module: user
    action: twitterSearch
    sf_format: json

profile:
  class: sfDoctrineRoute
  url: /user/:username
  options:
    model: sfGuardUser
    type: object
  param:
    module: user
    action: show

speakers:
  class: sfDoctrineRoute
  url: /:slug/speakers
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: speakers

presentation:
  class: sfDoctrineRoute
  url: /:speaker_slug/:slug
  options:
    model: Content
    method: findBySpeakerSlugAndSlug
    type: object
  param:
    module: presentation
    action: show

event_map:
  class: sfDoctrineRoute
  url: /:slug/map.:sf_format
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: map
    sf_format: json

event_speaker_add:
  class: sfDoctrineRoute
  url: /:slug/speakers/add/:username
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: addSpeaker

event_speaker_remove:
  class: sfDoctrineRoute
  url: /:slug/speakers/remove/:username
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: removeSpeaker
  requirements:
    sf_method: post

event_action:
  class: sfDoctrineRoute
  url: /:slug/:verb/:action
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
  requirements:
    action: attend|watch|favourite|organise|speak
    verb: do|dont
    sf_method: post

event:
  class: sfDoctrineRoute
  url: /:slug
  options:
    model: Event
    method: findBySlug
    type: object
  param:
    module: event
    action: show