default:
  http_metas:
    content-type: text/html

  metas:
    title: Speakr
    description:
    keywords:
    language: en
    robots: index, follow

  stylesheets:
    - main.css

  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js
    - main: {position: last}

  has_layout: true
  layout: layout