default:
  http_metas:
    content-type: text/html

  metas:
    title: Speakr
    description:
    keywords:
    language: en
    robots: index, follow

  stylesheets:
    - jquery-ui.css
    - main.css

  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js
    - http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js
    - jquery.timeago.js
    - date.format.js
    - main: {position: last}

  has_layout: true
  layout: layout