<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    speakr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {
  public function getTwitterAPIUrl() {
    return sfConfig::get('app_twitter_api_url').'/'.sfConfig::get('app_twitter_api_version').'/';
  }

  public function getProfileImage($size = 'normal') {
    return $this->getTwitterAPIUrl().'users/profile_image/'.$this->getUsername().'.json?size='.$size;
  }
}