<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('friend', array(
             'follower_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'following_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'follower_id',
              1 => 'following_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('friend');
    }
}