<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('city', 'id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('country', 'id', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->changeColumn('region', 'id', 'integer', '8', array(
             'primary' => '1',
             ));
    }

    public function down()
    {

    }
}