<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('city', 'city_region_id_region_id', array(
             'name' => 'city_region_id_region_id',
             'local' => 'region_id',
             'foreign' => 'id',
             'foreignTable' => 'region',
             ));
        $this->createForeignKey('region', 'region_country_id_country_id', array(
             'name' => 'region_country_id_country_id',
             'local' => 'country_id',
             'foreign' => 'id',
             'foreignTable' => 'country',
             ));
        $this->addIndex('city', 'city_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->addIndex('region', 'region_country_id', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('city', 'city_region_id_region_id');
        $this->dropForeignKey('region', 'region_country_id_country_id');
        $this->removeIndex('city', 'city_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->removeIndex('region', 'region_country_id', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
    }
}