<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('event', 'event_city_id_city_id', array(
             'name' => 'event_city_id_city_id',
             'local' => 'city_id',
             'foreign' => 'id',
             'foreignTable' => 'city',
             ));
        $this->addIndex('event', 'event_city_id', array(
             'fields' => 
             array(
              0 => 'city_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('event', 'event_city_id_city_id');
        $this->removeIndex('event', 'event_city_id', array(
             'fields' => 
             array(
              0 => 'city_id',
             ),
             ));
    }
}