<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('location');
        $this->removeColumn('event', 'location_id');
        $this->addColumn('event', 'city_id', 'integer', '20', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->createTable('location', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'country_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
              'location_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->addColumn('event', 'location_id', 'integer', '20', array(
             'notnull' => '1',
             ));
        $this->removeColumn('event', 'city_id');
    }
}