<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->renameColumn('conference', 'title', 'name');
    }

    public function down()
    {
        $this->renameColumn('conference', 'name', 'title');
    }
}