<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('presentation', 'event_id', 'integer', '20', array(
             'notnull' => '1',
             ));
        $this->changeColumn('presentation', 'content_id', 'integer', '20', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}