Conference:
  actAs:
    Sluggable: ~
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    website: string(255)
    image: string(255)
    icon: string(255)
  options:
    orderBy: name ASC

Event:
  actAs:
    Timestampable: ~
  columns:
    conference_id:
      type: integer(20)
      notnull: true
    tagline: string(50)
    date:
      type: timestamp
      notnull: true
    city_id:
      type: integer(20)
      notnull: true
    description: string()
    website: string(255)
    image: string(255)
    icon: string(255)
    hashtag: string(50)
    address: string(255)
    postcode: string(8)
  relations:
    Conference:
      local: conference_id
      foreign: id
      foreignAlias: Events
    City:
      local: city_id
      foreign: id
      foreignAlias: Events
    Attending:
      class: sfGuardUser
      refClass: Attendee
      local: event_id
      foreign: user_id
      foreignAlias: Attending
    Favouriters:
      class: sfGuardUser
      refClass: Favouriter
      local: event_id
      foreign: user_id
      foreignAlias: Favourites
    Organisers:
      class: sfGuardUser
      refClass: Organiser
      local: event_id
      foreign: user_id
      foreignAlias: Organising
    Speakers:
      class: sfGuardUser
      refClass: Speaker
      local: event_id
      foreign: user_id
      foreignAlias: Speaking
    Watchers:
      class: sfGuardUser
      refClass: Watcher
      local: event_id
      foreign: user_id
      foreignAlias: Watching
  options:
    orderBy: date ASC

City:
  actAs:
    Sluggable: ~
  columns:
    id:
      type: integer
      primary: true
    region_id:
      type: integer(20)
      notnull: true
    name:
      type: string(255)
      notnull: true
  relations:
    Region:
      local: region_id
      foreign: id
      foreignAlias: Cities
  options:
    orderBy: name ASC

Region:
  actAs:
    Sluggable: ~
  columns:
    id:
      type: integer
      primary: true
    country_id:
      type: integer(20)
      notnull: true
    name:
      type: string(255)
      notnull: true
  relations:
    Country:
      local: country_id
      foreign: id
      foreignAlias: Regions
  options:
    orderBy: name ASC

Country:
  actAs:
    Sluggable: ~
  columns:
    id:
      type: integer
      primary: true
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name ASC