Presentation:
  columns:
    event_id:
      type: integer(20)
      notnull: true
    content_id:
      type: integer(20)
      notnull: true
  indexes:
    event_id_content_id:
      fields:
        - event_id
        - content_id
      type: unique
  relations:
    Event:
      class: Event
      local: event_id
      foreign: id
      foreignAlias: Presentations
    Content:
      class: Content
      local: content_id
      foreign: id
      foreignAlias: Presentations
    Speakers:
      class: sfGuardUser
      refClass: PresentationUser
      local: presentation_id
      foreign: user_id
      foreignAlias: Speakers

PresentationUser:
  columns:
    presentation_id:
      type: integer(20)
      primary: true
    user_id:
      type: integer(20)
      primary: true
  relations:
    Presentation:
      class: Presentation
      local: presentation_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

Content:
  actAs:
    Sluggable: ~
    Timestampable: ~
  columns:
    title:
      type: string(255)
      notnull: true
    description:
      type: string()
      notnull: true
  options:
    orderBy: title ASC