sfGuardUser:
  relations:
    Attending:
      class: Event
      refClass: Attendee
      local: user_id
      foreign: event_id
      foreignAlias: Attending
    Favourites:
      class: Event
      refClass: Favouriter
      local: user_id
      foreign: event_id
      foreignAlias: Favouriters
    Organising:
      class: Event
      refClass: Organiser
      local: user_id
      foreign: event_id
      foreignAlias: Organisers
    Speaking:
      class: Event
      refClass: Speaker
      local: user_id
      foreign: event_id
      foreignAlias: Speakers
    Watching:
      class: Event
      refClass: Watcher
      local: user_id
      foreign: event_id
      foreignAlias: Watchers
    Presentations:
      class: Presentation
      refClass: PresentationUser
      local: user_id
      foreign: presentation_id
      foreignAlias: Speakers
    Following:
      class: sfGuardUser
      refClass: Friend
      local: follower_id
      foreign: following_id
      foreignAlias: Followers
  options:
    orderBy: first_name, last_name ASC

sfGuardUserProfile:
  actAs:
    Sluggable: ~
    Timestampable: ~
  columns:
    description: string(255)
    website: string(255)
    image: string(255)
    icon: string(255)
  relations:
    User:
      class: sfGuardUser
      local: id
      foreign: id
      foreignAlias: Profile
      foreignType: one

Attendee:
  columns:
    user_id:
      type: integer(20)
      primary: true
    event_id:
      type: integer(20)
      primary: true
  relations:
    Event:
      class: Event
      local: event_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

Favouriter:
  columns:
    user_id:
      type: integer(20)
      primary: true
    event_id:
      type: integer(20)
      primary: true
  relations:
    Event:
      class: Event
      local: event_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

Organiser:
  columns:
    user_id:
      type: integer(20)
      primary: true
    event_id:
      type: integer(20)
      primary: true
  relations:
    Event:
      class: Event
      local: event_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

Speaker:
  columns:
    user_id:
      type: integer(20)
      primary: true
    event_id:
      type: integer(20)
      primary: true
  relations:
    Event:
      class: Event
      local: event_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

Watcher:
  columns:
    user_id:
      type: integer(20)
      primary: true
    event_id:
      type: integer(20)
      primary: true
  relations:
    Event:
      class: Event
      local: event_id
      foreign: id
    User:
      class: sfGuardUser
      local: user_id
      foreign: id

Friend:
  columns:
    follower_id:
      type: integer(20)
      primary: true
    following_id:
      type: integer(20)
      primary: true
  relations:
    Follower:
      class: sfGuardUser
      local: follower_id
      foreign: id
    Following:
      class: sfGuardUser
      local: following_id
      foreign: id