<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    speakr
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends PluginsfGuardUserProfile {
  public function __call($method, $arguments) {
    if(in_array($method, array('getImage', 'getIcon'))) {
      if(parent::__call($method, $arguments) == null) {
        call_user_func_array(array($this, str_replace('get', 'set', $method)), array(call_user_func_array(array($this, $method.'Url'), array())));
        $this->save();
      }
    }

    return parent::__call($method, $arguments);
  }

  public function getIconUrl() {
    return $this->getProfileImageUrl('mini');
  }

  public function getImageUrl() {
    return $this->getProfileImageUrl('normal');
  }

  public function getProfileImageUrl($size = 'normal') {
    $web = new sfWebBrowser();
    $web->get($this->getTwitterAPIUrl().'users/profile_image/'.$this->getUser()->getUsername().'.json?size='.$size);
    $url = $web->getUrlInfo();
    return $url['scheme'].'://'.$url['host'].$url['path'];
  }

  public function getTwitterAPIUrl() {
    return sfConfig::get('app_twitter_api_url').'/'.sfConfig::get('app_twitter_api_version').'/';
  }
}